### ISSUE TITLE
Unable to transmit CAN messages using ValueCAN 4-1

### ISSUE THREAD

**Issue by arraypan** [intrepidcs/libicsneo#3] opened 2019-03-14 18:48 UTC
I wasn't able to transmit CAN message using ValueCAN 4-1, but It worked fine with ValueCAN 4-2.

**Comment by hollinsky-intrepid** [comment] 2019-03-15 17:24
Since we discussed this offline and were unable to reproduce the issue, I'm closing this thread

**Closed by hollinsky-intrepid** 2019-03-15 17:24 UTC
